spring:
  application:
    name: auth-service

mongo:
  host: localhost
  port: 27018
  login: admin
  password: pass
  authDatabase: admin
  database: auth-service-db

rabbit:
  user: admin
  password: pass
  virtualHost: /
  nodeAddresses: localhost:5672,localhost:5673,localhost:5674
  topology:
    exchanges:
      direct:
        task:
          name: task.direct.exchange
        event:
          name: event.direct.exchange
    queues:
      userAuthCreation:
        name: queue.user-auth.creation
        routingKey: task.create.user-auth
      userCreationCompensation:
        name: queue.user.creation-compensation
        routingKey: event.user-auth.creation-fail