spring:
  application:
    name: auth-service

mongo:
  host: localhost
  port: 27018
  login: admin
  password: pass
  authDatabase: admin
  database: auth-service-db

rabbit:
  user: admin
  password: pass
  virtualHost: /
  nodeAddresses: localhost:5672,localhost:5673,localhost:5674
  topology:
    create-user:
      exchangeName: auth-service-create-user
      queueName: auth-service-create-user
      routingKey: auth-service.user.new
    compensate-create-user:
      exchangeName: auth-service-compensate-create-user
      queueName: auth-service-compensate-create-user
      routingKey: auth-service.user.compensate
    delete-user:
      exchangeName: auth-service-delete-user
      queueName: auth-service-delete-user
      routingKey: auth-service.user.delete
