spring:
  application:
    name: auth-service

mongo:
  host: localhost
  port: 27018
  login: admin
  password: pass
  authDatabase: admin
  database: auth-service-db

rabbit:
  user: admin
  password: pass
  virtualHost: /
  nodeAddresses: localhost:5672,localhost:5673,localhost:5674
  topology:
    exchanges:
      user:
        name: auth-service-user
        queues:
          create:
            name: auth-service-create-user
            routingKey: auth-service.user.create
          initiate-create-compensate-transaction:
            name: auth-service-initiate-create-user-transaction
            routingKey: auth-service.user.create.initiate.compensation
          delete:
            name: auth-service-delete-user
            routingKey: auth-service.user.delete
