spring:
  application:
    name: saga-orchestrator

rabbit:
  user: admin
  password: pass
  virtualHost: /
  nodeAddresses: localhost:5672,localhost:5673,localhost:5674
  topology:
    exchanges:
      user:
        name: user-service-user
        queues:
          create:
            name: user-service-create-user-start
            routingKey: user-service.user.create.start
          create-continue-transaction:
            name: user-service-create-user-continue
            routingKey: user-service.user.create.continue
          delete:
            name: user-service-delete-user
            routingKey: user-service.user.delete
      auth:
        name: auth-service-user
        queues:
          create:
            name: auth-service-create-user
            routingKey: auth-service.user.create
          initiate-create-compensate-transaction:
            name: auth-service-initiate-create-user-transaction
            routingKey: auth-service.user.create.initiate.compensation
          delete:
            name: auth-service-delete-user
            routingKey: auth-service.user.delete
