spring:
  application:
  name: user-service

mongo:
  host: localhost
  port: 27017
  login: admin
  password: pass
  authDatabase: admin
  database: user-service-db

rabbit:
  user: admin
  password: pass
  virtualHost: /
  nodeAddresses: localhost:5672,localhost:5673,localhost:5674
  topology:
    create-user:
      exchangeName: user-service-create-user
      queueName: user-service-create-user
      routingKey: user-service.user.new
    continue-transaction-create-user:
      exchangeName: user-service-continue-transaction-create-user
      queueName: user-service-continue-transaction-create-user
      routingKey: user-service.user.new.continue
    delete-user:
      exchangeName: user-service-delete-user
      queueName: user-service-delete-user
      routingKey: user-service.user.delete