spring:
  application:
  name: user-service

mongo:
  host: localhost
  port: 27017
  login: admin
  password: pass
  authDatabase: admin
  database: user-service-db

rabbit:
  user: admin
  password: pass
  virtualHost: /
  nodeAddresses: localhost:5672,localhost:5673,localhost:5674
  topology:
    exchanges:
      direct:
        task:
          name: task.direct.exchange
        event:
          name: event.direct.exchange
    queues:
      userCreation:
        name: queue.user.creation
        routingKey: task.create.user
      userDeletion:
        name: queue.user.deletion
        routingKey: task.delete.user