spring:
  application:
  name: user-service

mongo:
  host: localhost
  port: 27017
  login: admin
  password: pass
  authDatabase: admin
  database: user-service-db

rabbit:
  user: admin
  password: pass
  virtualHost: /
  nodeAddresses: localhost:5672,localhost:5673,localhost:5674
  topology:
    exchanges:
      user:
        name: user-service-user
        queues:
          create:
            name: user-service-create-user-start
            routingKey: user-service.user.create.start
          create-continue-transaction:
            name: user-service-create-user-continue
            routingKey: user-service.user.create.continue
          delete:
            name: user-service-delete-user
            routingKey: user-service.user.delete